services:
  db:
    image: postgres:15
    container_name: ut_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio_storage
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # Console web
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: ut_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    build: 
      context: ./backend
      target: runtime
    container_name: spring_backend
    env_file:
      - backend/.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio
      - redis
    restart: unless-stopped
    volumes:
      - maven-cache:/root/.m2

  frontend:
    build: 
      context: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    env_file:
      - frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - npm-cache:/root/.npm
      - node-modules:/app/node_modules

volumes:
  pgdata:
  maven-cache:
  npm-cache:
  node-modules:
  minio-data:
  redis-data:

