services:
  db:
    image: postgres:15
    container_name: ut_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: spring_backend
    env_file:
      - backend/.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    env_file:
      - frontend/.env
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:

